# Generated by Django 2.2.10 on 2020-04-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectureCode', models.CharField(max_length=200)),
                ('contentRate', models.IntegerField(default=0)),
                ('presentationRate', models.IntegerField(default=0)),
            ],
        ),
    ]
