# Generated by Django 2.2.10 on 2020-04-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Vote',
        ),
    ]
