# Generated by Django 3.0.6 on 2020-05-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('lecture_code', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('presenter', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('TEO', 'Theoretical'), ('APP', 'Applied'), ('OTHER', 'OTHER')], max_length=20)),
            ],
        ),
    ]
