# Generated by Django 2.2.10 on 2020-04-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoteWeight',
            fields=[
                ('name', models.CharField(choices=[('CONTENT', 'CONTENT'), ('PRESENTATION', 'PRESENTATION')], max_length=20, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_vote', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('presentation_vote', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Event')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Voter')),
            ],
            options={
                'unique_together': {('voter', 'lecture')},
            },
        ),
    ]
