# Generated by Django 2.2.10 on 2020-05-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voter',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'lecture')},
        ),
    ]
